 version: '3.8'

 services:
  app:
    build:
      context: .
    container_name: app
    env_file:
      - ./docker/.my-env
    depends_on:
      - db
    ports:
      - "8085:8085"
  db:
    image: postgres
    restart: always
    container_name: db
    environment:
      POSTGRES_USER: $DB_USERNAME
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
